### ISSUE TITLE
Documentation bugs

### ISSUE THREAD

**Issue by adamjstewart** [microsoft/torchgeo#101]
This is a running list of bugs I've noticed in the documentation that need to be fixed.

- [x] Sections don't have permalinks
- [x] "Open in Colab" button is too wide: https://github.com/pytorch/pytorch_sphinx_theme/issues/140, https://github.com/pytorch/pytorch_sphinx_theme/pull/142
- [x] Fonts are missing, requiring hack to `requirements.txt`: https://github.com/pytorch/pytorch_sphinx_theme/issues/143
- [x] Dataset base class is incorrect: https://github.com/sphinx-doc/sphinx/issues/9607
- [x] Models and trainers are missing args/returns documentation
- [x] Tutorials don't run on Colab, need to clone from GitHub and install dependencies (or pip install once we release on PyPI)
- [x] Notes on how to download SEN12MS and So2Sat aren't showing up (https://github.com/microsoft/torchgeo/commit/3d3b903d94c9ada2f9e0e919f254d7a8406d7e25, https://github.com/microsoft/torchgeo/commit/fd4998b78737aad6924a7d67c912f01661f96839)
- [x] API docs show "Return type: None" for most functions, see if we can get rid of this (#277)
- [ ] In-line code missing off-color background (https://github.com/pytorch/pytorch_sphinx_theme/issues/130)
- [x] the "well-tested" and "linters" links are broken on the users/contributing page (6d5725056c2c7851e2dc9a47952e2cd884ed43a4)
- [ ] NAIP has no docs because docstrings aren't inherited from parent classes
- [x] BoundingBox docs aren't formatted correctly: https://torchgeo.readthedocs.io/en/latest/api/datasets.html#torchgeo.datasets.BoundingBox (#976)
- [ ] Nested lists have a lot of unnecessary whitespace: https://torchgeo.readthedocs.io/en/latest/api/datasets.html#torchgeo.datasets.SpaceNet1
- [x] Models have extra undocumented `parameters` defined
- [x] Trainer kwargs are showing up under `parameters`
- [ ] Versions popup menu appears on wrong side of the screen
- [x] Versions popup menu does not have release versions, only latest and stable
- [x] `__getitem__` is showing up before `__init__` because things are sorted alphabetically, we don't want this (#976)
- [x] `torchgeo.samplers.Units`: possible enum values not displayed (#976)
- [x] `torchgeo.datasets.RasterDataset`: class attributes not displayed (#976)

**Comment by calebrob6** [comment]
There is some incompatibility going on between the `pytorch_sphinx_theme` and `nbsphinx`. With `nbsphinx` enabled in conf.py:
- The sidebar navigation doesn't show expand/collapse buttons
- The sidebar navigation doesn't scroll with the page
- Sections don't have permalinks
- There are require.js errors on the page

**Comment by calebrob6** [comment]
^ the above issues I mentioned were resolved by adding `nbsphinx_requirejs_path = ""` in `docs/conf.py`

Some references:
- https://github.com/pytorch/pytorch_sphinx_theme/issues/148
- https://github.com/spatialaudio/nbsphinx/issues/599

**Comment by adamjstewart** [comment]
We could consider switching to the [trojanzoo_sphinx_theme](https://github.com/ain-soph/trojanzoo_sphinx_theme) which is forked off of pytorch_sphinx_theme but better maintained.

**Comment by adamjstewart** [comment]
If we do switch to trojanzoo_sphinx_theme, we'll be able to move `docs/requirements.txt` into `setup.cfg`

**Comment by adamjstewart** [comment]
> `__getitem__` is showing up before `__init__` because things are sorted alphabetically, we don't want this

I believe this is caused by https://github.com/sphinx-doc/sphinx/issues/9395. We're using the correct settings in our `conf.py`:
```python
autodoc_member_order = "bysource"                                                        
```
However, Sphinx doesn't know where to locate the source code because we override `__module__` in order for other things to work.

**Comment by robmarkcole** [comment]
There is an error in `trainers.ipynb`. The csv is created with upper case column names (e.g. train_RMSE). Cell fixed below:

```python
train_steps = []
train_rmse = []

val_steps = []
val_rmse = []
with open(os.path.join(experiment_dir, "tutorial_logs", "version_0", "metrics.csv"), "r") as f:
    csv_reader = csv.DictReader(f, delimiter=',')
    for i, row in enumerate(csv_reader):
        try:
            # train_rmse.append(float(row["train_rmse"]))
            train_rmse.append(float(row["train_RMSE"]))
            train_steps.append(i)
        except ValueError: # Ignore rows where train RMSE is empty 
            pass

        try:
            # val_rmse.append(float(row["val_rmse"]))
            val_rmse.append(float(row["val_RMSE"]))
            val_steps.append(i)
        except ValueError: # Ignore rows where val RMSE is empty
            pass
```

**Comment by calebrob6** [comment]
Thanks for the catch / report @robmarkcole! This is one of the few things that isn't tested... Fixed in #434

**Comment by adamjstewart** [comment]
I think we can close this issue. Most remaining issues are documented in the pytorch-sphinx-theme repo. I want to change this in #2006
