### ISSUE TITLE
SpaceNet datasets

### ISSUE THREAD

**Issue by ashnair1** [microsoft/torchgeo#159]
The [SpaceNet Dataset](https://spacenet.ai/datasets/) contains ~67,000 square km of very high-resolution imagery, >11M building footprints, and ~20,000 km of road labels spread over 7 datasets:

![spacenet](https://user-images.githubusercontent.com/32295036/134308708-13bf1b6f-289b-4c65-a887-81b336b5e51d.png)

- [x] [Spacenet 1: Building Detection v1](https://spacenet.ai/spacenet-buildings-dataset-v1/) (#129)
- [x] [Spacenet 2: Building Detection v2](https://spacenet.ai/spacenet-buildings-dataset-v2/) (#155)
- [x] [Spacenet 3: Road Network Detection](https://spacenet.ai/spacenet-roads-dataset/) (#480)
- [x] [Spacenet 4: Off Nadir Buildings](https://spacenet.ai/off-nadir-building-detection/) (#185)
- [x] [Spacenet 5: Automated Road Extraction & Route Travel TIme Estimation from Satellite Imagery](https://spacenet.ai/sn5-challenge/) (#263)
- [x] [Spacenet 6: Multi-Sensor All-Weather Mapping](https://spacenet.ai/sn6-challenge/)
- [x] [Spacenet 7: Multi-Temporal Urban Development Challenge](https://spacenet.ai/sn7-challenge/) (#241)

This issue is to track the addition of these datasets.

**Comment by adamjstewart** [comment]
Our conda-forge repo just caught the fact that the SpaceNet datasets import the `affine` library but we're missing a dependency on `affine` in `setup.cfg`. Is `affine` actually needed? If so, can you determine the minimum supported version and add it to `setup.cfg`?

**Comment by ashnair1** [comment]
I believe I only explicitly imported affine for type annotations. The image transform of a rasterio image object is an `Affine` object.

**Comment by isaaccorley** [comment]
This is a bit of a hack but could we just use 'from rasterio.transform import Affine' instead of 'from affine import Affine'?

**Comment by adamjstewart** [comment]
> I thought `setup.cfg` only includes direct dependencies of torchgeo and not its transitive dependencies.

Correct, but if you directly import affine, that makes it a direct dependency.

I actually like @isaaccorley's suggestion, let's do that as long as it passes mypy.

**Comment by adamjstewart** [comment]
@ashnair1 where are we at with SpaceNet 6? Would love to be able to close this issue.

**Comment by ashnair1** [comment]
SpaceNet 6 is currently unavailable on [Radiant MLHub](https://mlhub.earth/data/spacenet6). I had raised radiantearth/radiant-mlhub#93 to track this among other issues with the SpaceNet datasets. Will give them a ping.
