### ISSUE TITLE
Random sized patches support for other non-geospatial datamodules

### ISSUE THREAD

**Issue by nilsleh** [microsoft/torchgeo#855]
### Summary

In #851 it was suggested that datamodules with variable sized input images should implement a random size crop  from tile to patches during training and have a keyword argument to specify the desired `patch_size`.

When looking through our other Non-geospatial datamodules, there are other cases that might be good to add the same support, just because the default images are very large and not suitable for batches even though all images have the same dimensions:

- [x] GID-15, defaullt image size 6800x7200 (#928)
- [x] Inria Aerial Image Labeling, default image size 5000x5000
- [x] DeepGlobeLandCoverDataModule, default image size is 2,448x2,448 (#876)
- [x] Potsdam, default image size is 6000x6000 (#929)

Maybe, there can also be a threshold for future datamodule additions: for example if image size is greater than X, implement the random patch crop logic for that datamodule.

### Rationale

I think it would lower the threshold of using these datasets. Since datamodules are supposed to make it very quick and easy for users to conduct segmentation experiments, the patch_size logic would make it a bit more easier to practically use the datamodules right away.

### Implementation

Implement a logic like in the `OSCDDatamodule.`

**Comment by ashnair1** [comment]
The `InriaAerialImageLabelling` datamodule already supports extraction of random crops.
